name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build_and_push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      
      - name: downcase REPO
        run: echo "ACTOR1=${{github.actor}}"
        
      - name: downcase REPO
        run: echo "ACTOR=${ACTOR1,,}"

      - name: Print actor
        run: echo ${ACTOR}

      - name: Build the Docker image
        run: docker build -t my-image .

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Tag the image
        run: docker tag my-image ghcr.io/solomonboltin/my-image:latest

      - name: Push the image
        run: docker push ghcr.io/solomonboltin/my-image:latest
